void readArray(int data[], int size)
void readArray(double data[], int size)
void printArray(int data[], int size)
void printArray(int data[], int size)
void fillArray(int data[], int size, int value = 0)
void fillArray(double data[], int size, double value = 0)
void arrayCopy(int data1[], int size, int data2[])
void reverseArray(int data[], int size)
void combineArrays(int data1[], int& size1, int data2[], int size2) 